import Head from 'next/head'
import { Box, Heading, PageLayout } from '@primer/react'
import Navbar from '../components/Header';




export default function Home() {

  return (
    <>
      <Head>

        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Navbar />


      <PageLayout>

        <PageLayout.Header divider="line">
          <Box sx={{ padding: '10px' }} m={4}>
            <Heading sx={{ mb: 2 }} >Hello, world!</Heading>
            <p>This will get Primer text styles.</p>
          </Box>
        </PageLayout.Header>

        <PageLayout.Content>
          <Box sx={{ padding: '10px' }} m={4}>
            <Heading sx={{ mb: 2 }} >Hello, world!</Heading>
            <p>This will get Primer text styles.</p>
          </Box>
        </PageLayout.Content>

        <PageLayout.Footer divider="line">
          <Box sx={{ padding: '10px' }} m={4}>
            <Heading sx={{ mb: 2 }} >Hello, world!</Heading>
            <p>This will get Primer text styles.</p>
          </Box>
        </PageLayout.Footer>

      </PageLayout>
    </>
  )
}
